name: main
on: [push]
jobs:
  ci-test:
    runs-on: ubuntu-latest
    services:
      # mysql-service Label used to access the service container
      mysql-service:
        # Docker Hub image (also with version)
        image: mysql:latest
        env:
          ## Accessing to Github secrets, where you can store your configuration
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing_db
        ## map the "external" 33306 port with the "internal" 3306
        ports:
          - 3306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHP CodeSniffer Check with Annotations
        run: |
          ./vendor/bin/pint
      - name: Copy .env.ci to .env
        run: cp .env.ci .env
      - name: Execute migrations
        run: php artisan migrate:fresh --seed
      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing_db
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: root
        run: ./vendor/bin/pest
